### ISSUE TITLE
Hope to support 1Password log in

### ISSUE THREAD

**Issue by zhangweijie-cn** [jkpang/PPHub-Feedback#1]
I don't want to copy and paste my password from 1Password.
Hope can support 1Password or use SFSafariViewController to log in.

**Comment by jkpang** [comment]
Okay, I'll try to optimize this problem
**********************
好的,我会尝试优化这个问题 @zhangweijie-cn

**Comment by jkpang** [comment]
Today I use SFSafariViewController instead of WKWebView authorization login, password found automatic filling is indeed very good, but there is a problem: the user can not replace the other GitHub account, because Apple is not allowed to delete the Safari within the APP cookie, which can not enter the user login interface fill in the user name and password.
But I'll try to support 1Password. Thank you for your advice😊
*********************************************************
今天我使用了SFSafariViewController代替WKWebView进行授权登录后, 发现自动填充密码确实很好, 但是有一个问题: 用户不能更换其他GitHub账户 , 因为苹果不允许在APP内删除Safari的cookie, 从而无法进入用户登录界面填写用户名和密码. 
不过我会尝试支持 1Password, 谢谢你的建议😊

**Comment by zhangweijie-cn** [comment]
Thanks for your work, I just applied for the TestFlight test.

**Comment by jkpang** [comment]
Not at all, thank you for your feedback and support for PPHub @zhangweijie-cn

**Comment by jkpang** [comment]
The latest version has supported 1Password login @zhangweijie-cn
