### ISSUE TITLE
access token with private repo access, but no private repo displays

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#7]
PPHub gains full control of private repos through oauth access token, but none displays in my repo list. So is it not implemented yet? Otherwise, I doubt      the purpose of gain such access privilege.

运行环境: iPhone 6s - iOS11.1.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
PPHub authorized login completely according to the official GitHub OAuth2.0 authorized, there was no except GitHub outside of the API operation on the access token PPHub. The user access to all requests for API are the use of the official GitHub open API: https://developer.github.com/v3/. GitHub because I didn't have a paid account, temporarily can not test the private library. If you feel get private library the authority is not safe, the next version I will consider this permission to remove, thank you for your use 
================================
PPHub的授权登录完全按照GitHub官方的OAuth2.0授权进行的, 完全没有对用户获取的access token进行除GitHub API以外的操作. PPHub所有的请求API均使用GitHub官方开放的API: https://developer.github.com/v3/. 因为我没有GitHub付费账号, 暂时测试不了私有库. 如果您觉得获取私有库的权限不安全, 下个版本我会考虑把此权限移除, 感谢您的使用 
@Sorosliu1029

**Comment by Sorosliu1029** [comment]
我觉得PPHub挺好用的，希望可以由用户来选择是否授予私有库的访问。如果授予的话，在个人仓库列表中可以显示出来。

**Comment by jkpang** [comment]
哇, 这是一个很好的建议. 关于私有库获取权限后个人仓库列表看不到的问题, 我会想办法去解决(虽然我不能创建私有库), 非常感谢您的反馈! @Sorosliu1029

**Comment by jkpang** [comment]
V1.0.1 has passed the apple audit today, and the new version has repaired the problem
V1.0.1今天已通过苹果审核, 新版本已修复该问题

**Comment by Sorosliu1029** [comment]
我更新了新版本，还是没有显示私有仓库，退出登录之后重新登录也是一样没有。
取消oauth token授权之后，重新授权，问题仍然存在。
@jkpang

**Comment by jkpang** [comment]
恩恩, 我大概知道原因了. 那这样, 我给你的账号开通下内测权限, 我今晚下班回家上传一个内测版本, 留一下你的邮箱哈 @Sorosliu1029

**Comment by Sorosliu1029** [comment]
soros.liu1029@gmail.com

**Comment by jkpang** [comment]
方便的话可以加下我的QQ吗 2406552315 , 内测还需要其他一些信息, 方便交流

**Comment by Sorosliu1029** [comment]
开个slack或者gitter吧，QQ，微信比较私人

**Comment by jkpang** [comment]
![image](https://user-images.githubusercontent.com/17583451/33321741-b8bbfd30-d481-11e7-8b37-d46a25febf57.png)
测试版本已提交审核, 注意查收邮件哦~

**Comment by Sorosliu1029** [comment]
内测版仍然存在问题，重新登录，重新授权都没有解决

**Comment by jkpang** [comment]
不会吧，另一名用户之前也是私有库看不到，但是这次的测试版1.0.2(5)已经解决了

**Comment by jkpang** [comment]
您先把PPHub卸载了，然后重新安装测试版，再看看应该就有了，私有库是有一个🔒的标志的。

**Comment by Sorosliu1029** [comment]
嗯，现在有了。
之前判断‘没有解决’，是直接看了个人profile页面的repo数，没有点进去看。
另外，个人profile页面的repo数没有包含私人仓库，这应该也是个bug

**Comment by jkpang** [comment]
嗯嗯，是的，这个Bug我已经记下来了，感谢反馈，我下班后开始准备提交1.0.2正式版本的审核，感谢🙏🏻
